### ISSUE TITLE
[Audio]:(HQ) Epic Sax Guy loop

### ISSUE THREAD

**Issue by coolsnowmann** [retro-dev-rblx/Music#294]
### Check if this audio is already added to RetroStudio.

- [X] The audio is not already in game.

### Is this for the main-menu playlist?

- [ ] Add to main-menu playlist.

### Is this song from an old Roblox era or a sound effect?

- [X] This song is from old Roblox or is a sound effect.

### A link to the audio on Roblox

https://create.roblox.com/store/asset/130794684?externalSource=www

### A link to the audio file to download.

https://www.mediafire.com/file/2f6e7q4bzbfdob7/%2528HQ%2529_Epic_Sax_Guy_Loop.ogg/file
